### ISSUE TITLE
Can't get map to align centrally

### ISSUE THREAD

**Issue by daggewo** [GrandSir/InteractiveMap#7] opened 2023-09-28 08:03 UTC
Hello,

Thank you so much for this package. However I can't seem to align the map centrally in its parent view. It is always .leading.
Is is som inherent alignment that I can access?

Thanks in advance,
Dag

**Comment by grandsir** [comment] 2023-10-11 08:26
Closing this because it is a duplicate of #6. I'll look at it, thanks.

**Closed as completed by grandsir** 2023-10-11 08:26 UTC
